/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef volatile unsigned int vuint32_t;

#include <stdint.h>

//RCC
#define RCC_Base    0x40021000
#define RCC_APB2ENR *(vuint32_t *)( RCC_Base + 0x18)
#define RCC_IOPAEN  (1<<2)


//GPIO
#define GPIO_Base 0x40010800
#define GPIOA_CRH  *(vuint32_t *)(GPIO_Base + 0x04)
#define GPIOA_ODR  *(vuint32_t *)(GPIO_Base + 0x0C)
#define GPIOA_CRL  *(vuint32_t *)(GPIO_Base + 0x00)


//EXTI
#define EXTI_Base 0x40010400
#define EXTI_IMR  *(vuint32_t *)(EXTI_Base + 0x00)
#define EXTI_RTSR *(vuint32_t *)(EXTI_Base + 0x08)
#define EXTI_PR   *(vuint32_t *)(EXTI_Base + 0x14)

//AFIO
#define AFIO_Base    0x40010000
#define AFIO_EXTICR1 *(vuint32_t *)(AFIO_Base + 0x08)

#define NVIC_EXTI0 *(vuint32_t *)(0xE000E100)

void clock_init(void)
{
	//enable clock GPOIA
	RCC_APB2ENR |= RCC_IOPAEN;

	//Bit 0 AFIORST: Alternate function I/O rese
	RCC_APB2ENR |= (1<<0);
}

void GPIO_init()
{
	//pin13 portA output
	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=0x00200000;

}

int main(void)
{
	clock_init();
	GPIO_init();
	//EXTI0 configuration TO PORTA0
	AFIO_EXTICR1 =0;

	//enable rising trigger
	EXTI_RTSR |=(1<<0);

	//enable EXTI 0 (Mask = 1)
	EXTI_IMR  |=(1<<0);

	//pinA 0 floating
	GPIOA_CRL |= (1<<2);

	//enable NVIC IRQ6 EXTI0
	NVIC_EXTI0 |= (1<<6);

	while(1);
	return 0;
}

void EXTI0_IRQHandler()
{
	//IRQ is happened EXTI0 >> PORTA pin0 _| rising

	// toggle led pin13
	GPIOA_ODR ^= (1<<13);

	//clear pending register
	EXTI_PR |=(1<<0);
}
