/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


typedef volatile unsigned int vuint32_t;

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//registers address

#define GPIO_Base 0x40010800
#define GPIO_CRH *(vuint32_t *)(GPIO_Base + 0x04)
#define GPIO_ODR *(vuint32_t *)(GPIO_Base + 0x0C)

#define RCC_Base 0x40021000
#define RCC_APB2ENR *(vuint32_t *)( RCC_Base + 0x18)
#define RCC_CFGR *(vuint32_t *)( RCC_Base + 0x04)
#define RCC_CR *(vuint32_t *)( RCC_Base + 0x0)

typedef union{
	vuint32_t allfields;
	struct{
		vuint32_t reserved:13;
		vuint32_t pin_13:1;
	}pin;
}ODR_REG_t;

volatile ODR_REG_t* ODR_R = (volatile ODR_REG_t*)(GPIO_Base + 0x0C);
int main(void)
{
	// enable I/O port A clock
	RCC_APB2ENR |=1<<2;

	RCC_CFGR |= 0b10<<0; //pll on
	RCC_CFGR |= 0b0110<<18;// to set pll mul = 8
	RCC_CFGR |= 0b100<<8;   //to make ABP1=2
	RCC_CFGR |= 0b101<<11; //to make ABP2=4
	RCC_CR |= 1<<24; //pll as the sysclk


	GPIO_CRH &=0xff0fffff;
	GPIO_CRH |=0x00200000;
	while(1)
	{
		ODR_R->pin.pin_13=1;
		for(int i=0;i<50000;i++);
		ODR_R->pin.pin_13=0;
		for(int i=0;i<50000;i++);
	}
	return 0;
}
